a = int(input())
b = int(input())
c = int(input())
d = int(input())

print(a + b + d)
print(a * b * c * d)
print((a+c) * (b+d))
print(int(a/c))
print(a/b)
print(a%d)
print(a**(c*-1))
print(d**(1/2))
print((c/3)* (pow(a, b+(c/2))-1) + d)